package com.paqrap.simulador;

public enum TipoEvento {
    INICIO_SIMULACION,
    PLANIFICACION_RUTAS,
    DESPACHO_VEHICULO,
    MOVIMIENTO_TRAMO,
    LLEGADA_A_DESTINO,
    INICIO_SERVICIO,
    FIN_SERVICIO_ENTREGA,
    INCIDENCIA_BLOQUEO,
    INCIDENCIA_NUEVO_PEDIDO,
    REPLANIFICACION_RUTAS,
    SNAPSHOT_ESTADO,
    FIN_SIMULACION
}
