package com.paqrap.simulador;

public enum TipoEvento {
    INICIO_SIMULACION,
    PLANIFICACION_RUTAS,
    DESPACHO_VEHICULO,
    MOVIMIENTO_TRAMO,
    LLEGADA_A_DESTINO,
    INICIO_SERVICIO,
    FIN_SERVICIO_ENTREGA,
    INICIO_REFRIGERIO,
    FIN_REFRIGERIO,
    RETORNO_ALMACEN,
    LLEGADA_ALMACEN,
    INCIDENCIA_BLOQUEO,
    INCIDENCIA_AVERIA_VEHICULO,
    INCIDENCIA_NUEVO_PEDIDO,
    REPLANIFICACION_RUTAS,
    SNAPSHOT_ESTADO,
    FIN_SIMULACION
}
